// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh48SNwOQjTjnYWK18UDWum9DwluXLDH4',
    appId: '1:839694374515:android:374efbd5da4e87c25a7c06',
    messagingSenderId: '839694374515',
    projectId: 'maps-app-7678a',
    storageBucket: 'maps-app-7678a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRFrskgCqf_v31KpS508i-jeCxow5Bztc',
    appId: '1:839694374515:ios:9139feb84077ebc15a7c06',
    messagingSenderId: '839694374515',
    projectId: 'maps-app-7678a',
    storageBucket: 'maps-app-7678a.firebasestorage.app',
    iosBundleId: 'com.example.sayaraty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRFrskgCqf_v31KpS508i-jeCxow5Bztc',
    appId: '1:839694374515:ios:9139feb84077ebc15a7c06',
    messagingSenderId: '839694374515',
    projectId: 'maps-app-7678a',
    storageBucket: 'maps-app-7678a.firebasestorage.app',
    iosBundleId: 'com.example.sayaraty',
  );
}
